### PR TITLE
Add multithreading with OpenMP for STK brute forcing

### PR DESCRIPTION
**Pull request by JelteF**
Use OpenMP to add multithreading to the STK brute force loop. On my laptop (dualcore i5 with hyperthreading) it had a speedup of about 1.5.

### CODE REVIEW

**Comment by JelteF** [comment]
On my desktop (with a physical AMD quadcore without hyperthreadin) I got a speedup of about 3.

**Comment by mikeryan** [comment]
My only issue with this is that I'd like it to be an optional compile flag. Will this compile cleanly if -fopenmp is not present? If so we can just have it commented out, or perhaps make a new Makefile target for it such as crackle-openmp.

**Comment by JelteF** [comment]
Fair point, I just added a flag to ignore the unknown-pragmas warning in that case. If the `-fopenmp` flag is removed, it will still compile cleanly. I do not know how to make the `-fopenmp` flag itself optional though. And I'm also not sure what happens when you try to build with that flag enabled when gcc is built without openmp support.

**Comment by mikeryan** [comment]
Merging this with #15 opened to resolve the conditional compile.

**Pull request merged**
